### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by random-guy** [isomoar/json-editor#1]
Hi,

I'm creating a desktop http requests application (like postman) in Qt and I need a syntax highlighter for json. So I've searched to see if anyone have made anything and I found this yours project. I would love to use the one that you have written here:
https://github.com/isomoar/json-editor/blob/master/syntaxhighlightening/highlighter.cpp

I will only change some colors and I will give you full credit for it.

Any chance to add a license to this project so I can use the syntax highlighting part in my project? My project is not in github yet but it will be soon, so I can notify you if you want.

Thanks for reading and keep the great work.

random-guy

**Comment by isomoar** [comment]
Hi @random-guy, I just added a license file. Wishing you all the best with the project!

**Comment by random-guy** [comment]
Thank you very much! Much appreciated. :)
